.github/workflows/web-console.yml
packages/web-console/src/scenes/Footer/BuildVersion/index.tsx

This PR adds `.github/workflows/web-console.yml` which runs `yarn workspace @questdb/web-console run build` on each PR

web-console: add github action to build web-console

---

.github/workflows/web-console.yml
packages/web-console/package.json

- add npm publish job
- add publish config

web console automate npm publish

---

packages/react-components/CHANGELOG.md
packages/react-components/package.json
packages/react-components/src/components/Button/index.stories.tsx
packages/react-components/src/components/Button/index.tsx
packages/react-components/src/components/Heading/index.stories.tsx
packages/react-components/src/components/Heading/index.tsx

- add `dataHook` props to Button
- add dataHook prop to Heading
- bump version

react components/add data hook

---

packages/web-console/src/partials/import.hbs
packages/web-console/src/styles/_import.scss

This PR updates web console import dialog with a note about `COPY`
command

web-console: add note about CSV import throught COPY command

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

release @questdb/web-console@0.0.9
changelog
- grid is virtualized horizontally, fixed bunch of glitches, added column resize, added cell copy to clipboard shortcuts, updated visuals #75

web-console: release 0.0.10

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

release @questdb/web-console@0.0.11
Releasing changes from this PR: https://github.com/questdb/ui/pull/78

web-console: release 0.0.11

---

packages/web-console/src/js/console/grid.js
packages/web-console/src/styles/_grid.scss

fix: delayed grid resize and column value overspill

---

CODE_OF_CONDUCT.md
README.md
docs/local-development-setup.md
packages/react-components/README.md
packages/screenshot-tests/README.md
packages/web-console/README.md

This PR adds more documentation on how to get started to contribute to
the repository.
Each package requires the same bootstrap process, and it's described
once in a new file called `docs/local-development-setup.md`.
In addition this PR adds code of conduct document at `CODE_OF_CONDUCT.md`. It is the same as on [the main repository](https://github.com/questdb/questdb/blob/master/CODE_OF_CONDUCT.md).

docs(*): update readmes and local dev setup guides

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

- tidy-up grid visuals
- fix grid column resize glitches
- improve grid render performance by over 80%
- fix horizontal splitter resize issue https://github.com/questdb/ui/issues/36
- grid semantic highlighting for designated timestamp values
- grid semantic highlighting for null values

web-console: release 0.0.12

---

packages/web-console/src/js/console/grid.js
packages/web-console/src/styles/_grid.scss

https://user-images.githubusercontent.com/7276403/218837333-e7fcd9df-7bb3-49c8-baa1-136e2b38035e.mp4

feat(web-console): persist and re-use column layout over multiple SQL executions

---

packages/browser-tests/cypress/commands.js
packages/browser-tests/cypress/integration/console/editor.spec.js
packages/web-console/src/scenes/Editor/Monaco/questdb-sql/conf.ts

Changes in this PR are extracted from #100 
That PR includes a bug fix as well as tests refactoring. This PR is only about refactoring browser tests in an attempt to reduce CI flakyness.
It should help with merging other PRs like #105

test(web-console): refactor browser tests to reduce flakyness

---

packages/web-console/package.json

- grid rendering when switching from non-grid panel to grid (after windows resize with invisible grid)
- two focused cells (incorrect rendering)
- render bugs for very wide columns in the middle of table
- new grid controls in grid panel
- freeze left column controls
- shuffle columns to front controls
- improved visuals
Show & Tell:
https://user-images.githubusercontent.com/7276403/225041158-0cdf21a2-3a32-43c1-bb83-92b253a8de6d.mp4

web-console: release 0.1.0

---

packages/web-console/src/scenes/Result/index.tsx

fixed grid rendering issues on query text that required URL encoding

fix(grid): fix url encoding for grid pagination queries

---

packages/web-console/package.json

bugfix on top of https://github.com/questdb/ui/pull/111

web-console: release 0.1.1

---

packages/web-console/src/js/console/grid.js

crypto.subtle does not work on HTTP

chore(web-console): use local non-secure hash function instead of crypto.subtle

---

packages/web-console/package.json

- removed dependency on crypto lib

web-console: release 0.1.2

---

packages/web-console/package.json

release(web-console): 0.2.0

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

Changes as per [CHANGELOG.md](https://github.com/questdb/ui/blob/main/packages/web-console/CHANGELOG.md).

release(web-console): 0.2.2

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

Updated version number to 0.2.3.
Commit log:
* bump version to 0.2.3

release(web-console): 0.2.3

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

Bumped version to 0.2.4.
Commit log:
* bump version to 0.2.4

release(web-console): 0.2.4 

---

packages/web-console/src/js/console/grid.js

Fixes #167
fix the following rendering issue:
https://github.com/questdb/ui/assets/7276403/7e73d3d9-0b6e-47cb-a8da-621b4b4f2b4b

fix(grid): fix incorrect render of last few columns

---

packages/react-components/src/components/FeedbackDialog/index.tsx

Add an optional email field to the feedback form, so that the team can reach back to Web Console users (Cloud Feedback has email in the payload by default).

feat(react-components): Add optional `email` field to `FeedbackDialog`

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

Bumped version to 0.2.5.
Commit log:
- bump version to 0.2.5
- update changelog

release(web-console): 0.2.5

---

packages/web-console/src/scenes/Editor/Menu/index.tsx
packages/web-console/src/scenes/News/bell.tsx
packages/web-console/src/scenes/News/index.tsx
packages/web-console/src/theme/global-styles.ts

This PR is for #199
- refactor swing animation and extract to a component
- use `transparent` skin on help button
- reduce background color intensity on search box
| before | after |
| --- | --- |
| ![Screenshot 2023-10-05 at 15 23 17](https://github.com/questdb/ui/assets/4284659/e33e3948-7956-4994-a25a-4565b45a1524) | ![Screenshot 2023-10-05 at 15 17 55](https://github.com/questdb/ui/assets/4284659/8b7c60a3-fd61-42d0-bd4f-9eae779b5b45)|
https://github.com/questdb/ui/assets/4284659/d06a042d-a9c3-4358-90e7-27598f13f485
https://github.com/questdb/ui/assets/4284659/6765d7ad-457a-4e3e-9479-bf23c4071e24

web console news ui tweak

---

packages/react-components/src/components/DropdownMenu/index.tsx

Needed to properly manage positioning (index) in certain cases.

chore(react-components): add `Portal` module to `DropdownMenu`

---

packages/web-console/src/components/CreateTableDialog/index.tsx
packages/web-console/src/components/ToggleButton/index.tsx
packages/web-console/src/scenes/Console/index.tsx

Disable the Create Table and Import CSV feature in read-only mode.

chore(web-console): add read-only mode in the UI

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

- allow ampersand in the grid output [#222](https://github.com/questdb/ui/pull/222)
- Disable create table/import UI in read-only mode [#221](https://github.com/questdb/ui/pull/221)

release(web-console): 0.3.0

---

packages/web-console/src/scenes/Layout/help.tsx

Closes #224.
NB that this is a pretty trivial change, and can be just as easily be resolved as a wontfix.

feat(web-console): Add menu item for StackOverflow

---

packages/web-console/package.json
packages/web-console/src/scenes/Layout/help.tsx
packages/web-console/webpack.config.js

Add an info and link to the Web Console commit hash to help debugging issues.

feat(web-console): add commit hash info

---

packages/web-console/src/components/ToggleButton/index.tsx
packages/web-console/src/components/icons/import.tsx
packages/web-console/src/scenes/Console/index.tsx

Update Import pane CTA icon to unify between it and the panel itself.

chore(web-console): new Import icon

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

- Enhanced SQL editor autocomplete [#241](https://github.com/questdb/ui/pull/241)
- Commit hash info [#249](https://github.com/questdb/ui/pull/249)
- CSV Import disclaimer texts [#229](https://github.com/questdb/ui/pull/229)
- Replace jQuery event bus with eventemitter3 [#250](https://github.com/questdb/ui/pull/250)
- New Import icon [#258](https://github.com/questdb/ui/pull/258)
- Fix issues with Run button in editor gutter [#257](https://github.com/questdb/ui/pull/257)
- Fix results and editor panel size configs [#260](https://github.com/questdb/ui/pull/260)

release(web-console): 0.3.3

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

- Added logic around authorization
[#272](https://github.com/questdb/ui/pull/272)
- Align varchar columns left, yarn4 migration
[#269](https://github.com/questdb/ui/pull/269)
- Do not trigger autocomplete on newlines
[#267](https://github.com/questdb/ui/pull/267)
- Get rid of autocomplete duplicates
[#268](https://github.com/questdb/ui/pull/268)
- File settings not being passed on to CSV upload
[#271](https://github.com/questdb/ui/pull/271)
- Capture exception if CSV Copy availability check fails
[#273](https://github.com/questdb/ui/pull/273)
- Show an icon next to non-designated timestamp columns
[#279](https://github.com/questdb/ui/pull/279)

release(web-console): 0.4.0

---

packages/web-console/package.json
packages/web-console/src/providers/QuestProvider/index.tsx

chore(web-console): start telemetry

---

packages/web-console/src/providers/QuestProvider/index.tsx
packages/web-console/src/store/Telemetry/epics.ts

chore(web-console): ent telemetry

---

.editorconfig
packages/web-console/src/modules/OAuth2/views/login.tsx
packages/web-console/src/providers/AuthProvider.tsx
packages/web-console/src/providers/QuestProvider/index.tsx
packages/web-console/src/store/Telemetry/epics.ts
packages/web-console/src/utils/localStorage/types.ts

This shows a login form when QuestDB has HTTP auth enabled. 
depends on https://github.com/questdb/questdb/pull/4672

feat(web-console): show login dialog for QuestDB OSS when acl is enabled

---

packages/web-console/package.json
packages/web-console/src/providers/AuthProvider.tsx

Send the correct redirect URI to the token endpoint.

fix(web-console): fix OAuth2 redirect URI + release 0.4.5

---

packages/web-console/CHANGELOG.md

chore(web-console): update change log

---

packages/browser-tests/cypress/integration/console/navbars.spec.js
packages/web-console/src/scenes/Layout/help.tsx

Add a link to public community forum.

chore(web-console): Add Discourse link to `Help` menu

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

- Community forum in Help menu [#312](https://github.com/questdb/ui/pull/312)
- Charts not working when using Auth
[#310](https://github.com/questdb/ui/pull/310)

release(web-console): 0.5.1

---

packages/browser-tests/cypress/integration/console/schema.spec.js
packages/web-console/src/components/TableSchemaDialog/dialog.tsx

Resolves: #324 
* Allow the web console to handle all cases of table names.
* Example: Table Name student and Student must be treated the same.

feat(web-console): Fix the response to handle all case of table name

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

- Handle line comments in SQLs [#333](https://github.com/questdb/ui/pull/333)
- Handle comments in SQL editor highlights
[#335](https://github.com/questdb/ui/pull/336)
- Tab state update issues that lead to visual side effects
[#337](https://github.com/questdb/ui/pull/337)
- Tab History UI updates [#335](https://github.com/questdb/ui/pull/335)

release(web-console): 0.6.1

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

- UX improvements around editor [#338](https://github.com/questdb/ui/pull/338)
- Running query is not cancelled when Run button is clicked
- Support for notice responses from server, such as empty SQL notice [#334](https://github.com/questdb/ui/pull/334)

release(web-console): 0.6.2

---

packages/web-console/src/scenes/Schema/index.tsx

required due to https://github.com/questdb/questdb/pull/5206

chore(web-console): use a new information_schema.questdb_columns() instead of information_schema.columns()

---

packages/web-console/CHANGELOG.md
packages/web-console/src/scenes/Editor/Monaco/tabs.tsx

Tiny fix to change an absolute url to relative.

chore(ui): change absolute url to relative

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

release(web-console): 0.7.2

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

release(web-console): 0.7.4

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

release(web-console): 0.7.5

---

packages/web-console/src/providers/SettingsProvider/index.tsx
packages/web-console/src/store/Telemetry/epics.ts
packages/web-console/src/utils/localStorage/types.ts

chore(ui): ent telemetry

---

packages/web-console/src/utils/copyToClipboard.ts

Resolves https://github.com/questdb/ui/issues/362

fix(web-console): workaround for broken safari copy schema mechanism
