packages/web-console/package.json
packages/web-console/webpack.config.js

- refactor config constants
- add `files` to package.json

releasable web console

---

packages/web-console/src/store/Telemetry/epics.ts

set a limit of 10000 latest records, to prevent possibility of excessive amount of rows

web-console: add `LIMIT -10000` to telemetry query

---

.github/workflows/web-console.yml

This PR, once merged, should trigger `npm publish` to work

release(web-console): 0.0.2

---

packages/web-console/src/scenes/Schema/Table/ContextualMenu/index.tsx

The reason why Safari did silently block copy to clipboard action irrespective of used method is because of an async promise being resolved on click first. It appears the copy has to be invoked directly in the onClick handler, otherwise it's getting ignored without warning.
The fix fetches the table schema upon opening the context menu and makes sure the copy option is available only when data is ready.

Fix clipboard action on Safari

---

packages/web-console/src/scenes/Footer/BuildVersion/index.tsx

This PR adds a check (`release.name`) to ensure the release data is correct, as we might hit rate limiter from time to time in which case the response structure is different.
The only important changed parts are here:
https://github.com/questdb/ui/pull/31/files#diff-5f27464970cc71e6fe74e7e42ba0a9051683d64f1528ed8034f1049f8530c89dR82-R84
Other changes are Prettier formatting which for some reason were missing last time.

web-console/check github api response

---

packages/browser-tests/cypress/integration/console/editor.spec.js
packages/web-console/CHANGELOG.md
packages/web-console/src/scenes/Editor/Monaco/index.tsx

Detect if a query passed via URL param already exists in the editor buffer and instead of duplicating, highlight the first match.
Tests - to be added

Do not duplicate existing queries when appending via URL param

---

packages/web-console/CHANGELOG.md
packages/web-console/src/scenes/Editor/Monaco/index.tsx

This PR adds three features:
- Highlighting active query at the point of cursor by a green vertical line. This is what will be executed upon clicking `Run` or by hitting the keyboard shortcut.
- Highlighting erroneous query in red
- Display a play arrow button on the first line of an active query - when clicked, it will evaluate the statement.
- Breakpoint-like line error indication
Screen recording:
https://user-images.githubusercontent.com/1871646/192565870-addd5f92-c1ac-4668-9658-261b264313a4.mp4
Error query highlight:
Breakpoint-like error indication:

Add query highlights to editor

---

packages/web-console/src/js/console/grid.js
packages/web-console/src/scenes/Notifications/index.tsx

This PR adjusts the way viewport is calculated in the results grid.
The calculation is later used in `activeRowDown` function. Previously it
was hardcoded, leading to a scenario where user was able to click arrow
down or page down key and highlight arrow below viewport area. As a
result active arrow was below visible area.
with this change the constants used in calculation are no longer
hardcoded, thus the positioning of highlighted row is correct

web-console: fix arrow down button positioning in grid logs

---

packages/web-console/src/scenes/Editor/Monaco/index.tsx
packages/web-console/src/scenes/Editor/Monaco/utils.ts

- set explicit line ending for `getQueryFromCursor`
- extract repetitive `findMatches` to `utils`
most importantly, this fixes the issue when wrong query is marked by the green gutter marker. This was apparent only on Windows.
before:
text cursor is on the second query, but green gutter is marking the first one.
after:
text cursor is on the second query and green gutter correctly marks it.

web-console: fix line ending match on windows

---

packages/web-console/src/scenes/Schema/Row/index.tsx
packages/web-console/src/scenes/Schema/Table/ContextualMenu/index.tsx
packages/web-console/src/scenes/Schema/Table/ContextualMenu/services.ts
packages/web-console/src/scenes/Schema/Table/index.tsx
packages/web-console/src/scenes/Schema/index.tsx
packages/web-console/src/utils/questdb.ts

This PR does two things:
- Adds an indication to the left of the table name if [WAL](https://en.wikipedia.org/wiki/Write-ahead_logging) is enabled for it.
- Adds `WAL` statement to table schema in the same scenario.

feat(ui): Add WAL indication

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

release `@questdb/web-console@0.0.9`
changelog
- add icon next to WAL enabled tables [#73](https://github.com/questdb/ui/pull/73)
- highlight `EXPLAIN` keyword in web console [#74](https://github.com/questdb/ui/pull/73)

web-console: release 0.0.9

---

packages/web-console/README.md
packages/web-console/src/js/console/grid.js
packages/web-console/src/scenes/Result/index.tsx
packages/web-console/src/styles/_grid.scss

On wide tables or SQLs producing large number of columns the existing grid struggles. That is both render and navigate the data. This implementation renders fixed number of HTML elements that are reused as grid is navigated.
- hover is disabled when grid is scrolled and re-enabled when scrolling stops
- fixed glitch causing  unexpected left-right scrolling. To reproduce on master, jump to end of dataset, scroll few rows up and scroll window left or right. You can see that active row jumps to bottom of the grid as you scroll left and right
- grid no longer uses `pct` for column width if columns do not fill the canvas, new grid looks like this:
- ~~grid resize doesn't change virtual windows size~~
- ~~column resize~~
- row number column
- ~~header restyling~~
- ~~copy cell value into …

feat: grid horizontal virtualization

---

packages/web-console/src/js/console/grid.js
packages/web-console/src/styles/_grid.scss
packages/web-console/src/styles/_navigation.scss

- type is subtext in column header
- column header is a little taller
- blank "grooves" around header as drag handles
- designated timestamp columns is highlighted in green
- column resize fixed as in when columns get narrower and by that do not fill entire viewport - the virtual cells are re-rendered and subsequent glitches fixed
- column width is rendered based on first 1000 rows of data

feat: updated grid visuals

---

packages/web-console/src/components/Splitter/index.tsx
packages/web-console/src/scenes/Layout/index.tsx

This commit simplifies the logic of positioning the splitter in
accordance to min/max setting.
With this fix, the splitter is not able to move past window size, and as
a result this makes split elements (table schema sidebar and grid)
always available for resizing.
closes #36

fix(web-console): fix and refactor `handleMouseMove` handler

---

packages/web-console/src/consts/index.ts
packages/web-console/src/store/Telemetry/epics.ts

Push WAL write telemetry as aggregated events with different origins
- `origin=1000` total row count written to WAL tables in thousands
- `origin=2000` total commits written to WAL tables
- `origin=3000` max commit write latency in seconds
WAL telemetry is aggregated by hour, so there will be max 3 rows per every hour.
All values are capped to max short 32767 value.
WAL telemetry is described at https://github.com/questdb/questdb/pull/2930

chore(wal): add wal telemetry to telemetry tracking

---

packages/web-console/src/scenes/Editor/Monaco/questdb-sql/createSchemaCompletionProvider.ts
packages/web-console/src/scenes/Editor/Monaco/utils.ts
packages/web-console/src/scenes/Schema/Row/index.tsx

Fixes #71
Fixes https://github.com/questdb/questdb/issues/1917
Also double quotes the table name on schema completion, as it's correct Postgres syntax and should be preferable. Single quoting works but it's QuestDB specific and confusing with string literals.

fix(web-console): fix sql editor error highlighting and code completions

---

.github/workflows/web-console.yml
packages/browser-tests/cypress.config.js
packages/browser-tests/cypress/commands.js
packages/browser-tests/cypress/integration/console/editor.spec.js
packages/web-console/serve-dist.js

This PR makes cypress tests written in `packages/browser-tests` to run in CI during PR builds.
Example run can be seen on
* [`checks` of this PR](https://github.com/questdb/ui/pull/103/checks)
* https://github.com/questdb/ui/actions/runs/4179369686/jobs/7239237886

test(web-console): run browser-tests in CI

---

packages/web-console/src/scenes/Import/ImportCSVFiles/table-schema/column.tsx
packages/web-console/src/scenes/Import/ImportCSVFiles/table-schema/columns.tsx

Previously, all schema edits have been locked on existing tables. This PR allows user to change column type and associated properties (designated timestamp etc)>
Existing table schema:

chore(web-console): allow editing column types on existing tables

---

packages/web-console/src/scenes/Import/ImportCSVFiles/table-schema/column.tsx

This PR updates the Columns editor shown in CSV import schema edit drawer.
* show `designated` timestamp button only for `column.type === 'TIMESTAMP` (previously shown for all)
* instead of button with icon, use button with checkmark and text. This is to make it more obvious that the button acts as a toggle
* add zebra colors to make it easier to visually distinguish between rows
* tweak layout: make `name` field wider than fixed-width `type` field
| Before | After |
| --- | --- |
| ![image](https://github.com/questdb/ui/assets/4284659/32309319-ab1b-46a4-a21a-9f3feef79032) | <img width="380" alt="Screenshot 2023-05-18 at 11 49 27" src="https://github.com/questdb/ui/assets/4284659/460b33e8-6f63-4276-98db-1a5f7040725e"> |

chore(web-console): update ui of columns in CSV import schema edit dialog

---

packages/web-console/src/scenes/Import/ImportCSVFiles/index.tsx

Previous "paste" implementation required the page wrapper to be in focus, i.e. user had to click within it first.
This more general approach works right upon clicking the "Import" button on the navbar, going back to browser tab, etc.

chore(web-console): allow pasting without page focus in import

---

packages/web-console/src/scenes/Import/ImportCSVFiles/dropbox.tsx
packages/web-console/src/scenes/Import/ImportCSVFiles/index.tsx
packages/web-console/src/scenes/Import/ImportCSVFiles/upload-settings-dialog.tsx

This PR adds handling of adding multiple files of the same name to the upload queue. The current version is buggy and does not inform the user if a duplicate has been detected.
The new behavior is as follows:
- Duplicate file names are allowed as long as the target table name is unique
- If duplicates have been found, a relevant error message is displayed
- Duplicates are filtered out before adding the batch to the queue.
Side changes:
- Paste event handler has been moved to `Dropbox`, so that the de-duplication logic is unified and displays the same error message every time for file browsing, drag & drop and paste.
Screen recording:
https://github.com/questdb/ui/assets/1871646/662764ec-c1e5-48a3-9f66-8a2c6b4c24a4

chore(web-console): Import: Handle duplicate files

---

packages/browser-tests/cypress/commands.js
packages/browser-tests/cypress/integration/console/editor.spec.js
packages/web-console/src/scenes/Editor/Monaco/index.tsx
packages/web-console/src/scenes/Editor/Monaco/utils.ts
packages/web-console/src/scenes/Import/index.tsx

After a successful import is performed we refresh the table list and execute a select query from the newly created/updated table. If an editor cursor is within a query before going to the Import page, the query execution might break.
Fixes:
- Expose `AppendQueryOptions` to the bus event
- Append query at the end of the editor buffer.

fix(web-console): fix executing selects after import

---

.github/workflows/ci.yml

This PR updates `.github/workflows/ci.yml file to:
* use generic names for CI steps, to fit monorepo and not only web-console package
* add publish script for react-components package, to allow automated publish when bumping version in `packages/react-components/package.json`

add publish script for `react-components` package

---

packages/react-components/src/components/Switch/index.tsx

This PR changes the colors of `<Switch>` component distributed by `@questdb/react-components` package

react-components: change colors of Switch to be more neutral

---

packages/web-console/src/scenes/Footer/BuildVersion/index.tsx
packages/web-console/src/scenes/Footer/BuildVersion/services.ts

Added variations of enterprise versions for the build button visible at the lower right corner.
button display depends on the output of `select build` command.
```
Build Information: QuestDB 7.2, JDK 17.0.7, Commit Hash da47b26f74125e28a5685c174390f7704f88b21a
```
---
```
Build Information: QuestDB Enterprise 1.1.0, JDK 17.0.7, Commit Hash da47b26f74125e28a5685c174390f7704f88b21a
```
---
```
Build Information: QuestDB Enterprise Pro 1.1.0, JDK 17.0.7, Commit Hash da47b26f74125e28a5685c174390f7704f88b21a
```
---
```
Build Information: QuestDB Enterprise Ultimate 1.1.0, JDK 17.0.7, Commit Hash da47b26f74125e28a5685c174390f7704f88b21a
```
Commit log:
* display different button for enterprise versions

chore(web-console): product button as reported by the database

---

packages/web-console/src/scenes/Footer/BuildVersion/index.tsx

- Ensure we are only checking for new releases if the user is on an open-source version.
- Fix an issue causing the check to fire twice, firing first when the `useState` default is set, and, subsequently, when build info is parsed.

chore(web-console): Only check for new releases on OSS

---

packages/react-components/src/components/FeedbackDialog/index.tsx

Instead of passing a prop, the submitting state is now handled inside the component.

chore(react-components): Handle submitting state inside `FeedbackDialog` component

---

packages/web-console/src/scenes/Footer/BuildVersion/index.tsx
packages/web-console/src/scenes/Footer/BuildVersion/services.ts

Update version label for unreleased local QuestDB package
Commit log:
* display `QuestDB Dev` instead of `QuestDB Dev 0.0.0` as version label for unreleased local QuestDB package

fix(web-console): Update version label for local QuestDB package

---

docs/local-development-setup.md

I have no idea if that's the best way. but just following the guide did not work for me, the web-console build was missing the react-components and I figured out this could help. It did.

chore(web-console) Add react-component builds to instructions

---

packages/web-console/src/components/TableSchemaDialog/dialog.tsx
packages/web-console/src/scenes/Import/ImportCSVFiles/files-to-upload.tsx
packages/web-console/src/scenes/Import/ImportCSVFiles/index.tsx
packages/web-console/src/scenes/Import/ImportCSVFiles/rename-table-dialog.tsx
packages/web-console/src/scenes/Import/ImportCSVFiles/types.ts
packages/web-console/src/scenes/Import/ImportCSVFiles/upload-actions.tsx
packages/web-console/src/scenes/Import/ImportCSVFiles/utils.ts

Allow writing to the same target table name from different files.
This PR makes sure each file added to the queue is treated as a separate entity and there are no glitches in the UI.
https://github.com/questdb/ui/assets/1871646/9eef49e2-d14d-4974-a0b3-fd0d5cb9abc8

chore(web-console): support writing multiple files to the same target

---

packages/web-console/src/js/console/grid.js

fixes:
https://github.com/questdb/ui/assets/7276403/7b4b95cb-d69a-4e01-a3af-1dd34073b762

fix(grid): fix render crash when grid is empty

---

packages/web-console/src/scenes/Schema/index.tsx
packages/web-console/src/utils/index.ts
packages/web-console/src/utils/isServerError.ts
packages/web-console/src/utils/questdb.ts

431 raised from too long query no longer removes table
closes: https://github.com/questdb/ui/issues/97
solution implemented: check for 431 for too large query and don't set error if so, since the only thing the error was doing in this component is conditionally rendering error message there shouldn't be side-effects

fix(web-console): keep table when 431 raised

---

packages/web-console/src/components/TableSchemaDialog/dialog.tsx
packages/web-console/src/scenes/Editor/Monaco/questdb-sql/createSchemaCompletionProvider.ts
packages/web-console/src/scenes/Import/ImportCSVFiles/index.tsx
packages/web-console/src/scenes/Schema/Table/index.tsx
packages/web-console/src/scenes/Schema/index.tsx
packages/web-console/src/utils/questdb.ts

linked to https://github.com/questdb/questdb/pull/3857 
QuestDB's `tables()` returns now `table_name` instead of `table`. This PR addresses this conundrum

chore(web-console): rename Table.name to Table.table_name

---

packages/web-console/src/utils/questdb.ts

This PR includes a fix for the `showTables` function to ensure backwards compatibility with the `name` property. The upcoming versions of QuestDB will change the column name from `name` to `table_name` for the `tables()` query. 
The web console has already started using the `table_name` property, but it's crucial to maintain compatibility with older versions of QuestDB. 
Please note that this backwards compatibility code can be removed once the new version of QuestDB is released.
Commit log:
* fix `showTables` to be backwards compatible with `name` property
Upcoming QuestdB versions will change the column name from `name` -> `table_name` for `tables()` query.
The web console is already using `table_name` property, but it should be backwards compatible with older versions of QuestDB.
Once …

Fix `showTables` for Backwards Compatibility with `name` Property in QuestDB

---

packages/web-console/src/components/Splitter/index.tsx
packages/web-console/src/scenes/Console/index.tsx
packages/web-console/src/scenes/Layout/index.tsx
packages/web-console/src/styles/_base.scss
packages/web-console/webpack.config.js

| Before | After |
|:-:|:-:|
| ![Screen Shot 2023-10-30 at 17 24 44](https://github.com/questdb/ui/assets/17235417/5ff73105-1172-4ec7-bc56-902b0ebc7d0f) | ![Screen Shot 2023-10-30 at 17 25 01](https://github.com/questdb/ui/assets/17235417/042f0c86-8c8e-4a2d-a3eb-c0f4713cd934) |
(viewport height: `330px`)
Also harder to show, but the **File queue** view is now scrollable in both axes on sufficiently small viewports/panel sizes.
The strangest "hack" of these changes is the addition of:
```js
const Bottom = styled.div`
display: flex;
flex: 1;
+ min-height: 0px;
`
```
But, doing so allows each panel of the editor to handle its own resizing strategy in a way that should be appropriate.

Enable HMR for CSS and improve overflow behaviour of bottom panel

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

- General UI refresh, new News UI, new CSV Import UI [#199](https://github.com/questdb/ui/pull/199)
- Enable HMR for CSS and improve overflow behaviour of bottom panel [#214](https://github.com/questdb/ui/pull/214)
- Rename Table.name to Table.table_name [#212](https://github.com/questdb/ui/pull/212)
- Escape HTML characters in the grid [#218](https://github.com/questdb/ui/pull/218)
- Fix showTables for Backwards Compatibility with name Property in QuestDB [#213](https://github.com/questdb/ui/pull/213)

release(web-console): 0.2.9

---

packages/web-console/src/js/console/grid.js

This PR allows ampersands in the grid cells, thus ensuring `explain` will be rendered properly.
| Before | After |
|--------|--------|
| ![CleanShot 2023-11-08 at 17 58 18@2x](https://github.com/questdb/ui/assets/1871646/fb8cdf23-abe6-4437-bbdc-ff28cb3c1f36) | ![CleanShot 2023-11-08 at 17 56 59@2x](https://github.com/questdb/ui/assets/1871646/824e45ac-d3f1-4876-98ea-ff6a27ec6962) |

fix(web-console): allow ampersand in the grid output

---

packages/web-console/src/components/TopBar/version.tsx

Add user info next to the instance name (if available, not set on the screenshot below).

feat(web-console): add `current_user` info in the top bar

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

- Add current_user info in the top bar [#225](https://github.com/questdb/ui/pull/225)
- Update pane splitters to real-time [#220](https://github.com/questdb/ui/pull/220)
- Add 'return to Cloud' button [#232](https://github.com/questdb/ui/pull/232)
- Update SQL Grammar to v1.0.14 [#233](https://github.com/questdb/ui/pull/233)

release(web-console): 0.3.1

---

packages/web-console/src/components/TableSchemaDialog/dialog.tsx

Closes [#3966](https://github.com/questdb/questdb/issues/3966)
The root cause of this issue was the automated code refactoring during changing `name` to `table_name` column in `tables()` query, which erroneously replaced the column name comparator in schema edit form:
https://github.com/questdb/ui/pull/212/files#diff-97f13119f61120692e5d36c4a5ced7f17163d6b7e531c0918a74372ef03bb713R145
```diff
- .unique((a, b) => a.name === b.name)
+ .unique((a, b) => a.table_name === b.table_name)
```

fix(web-console): fix table schema form on already existing tables

---

packages/web-console/src/components/CreateTableDialog/index.tsx
packages/web-console/src/scenes/Schema/Table/ContextualMenu/index.tsx
packages/web-console/src/scenes/Schema/Table/ContextualMenu/services.ts
packages/web-console/src/scenes/Schema/Table/index.tsx
packages/web-console/src/scenes/Schema/index.tsx
packages/web-console/src/utils/formatTableSchemaQuery.ts
packages/web-console/src/utils/pick.ts
packages/web-console/src/utils/questdb.ts

Closes https://github.com/questdb/ui/issues/184
If [`DEDUP UPSERT KEYS(key1, key2)`](https://questdb.io/docs/concept/deduplication/#example) has been used when creating a table, it should also be included in the generated DDL statement in `Copy schema to clipboard`.
Steps to test:
1. Create a table that has deduplication enabled
```sql
CREATE TABLE TICKS (
ts TIMESTAMP,
tk SYMBOL,
p DOUBLE
) TIMESTAMP(ts) PARTITION BY DAY WAL
DEDUP UPSERT KEYS(ts, tk);
INSERT INTO TICKS VALUES ('2023-07-14', 'QQQ', 78.56);
INSERT INTO TICKS VALUES ('2023-07-14', 'AAA', 78.56);
INSERT INTO TICKS VALUES ('2023-07-14', 'QQQ', 78.56); -- this is a dupe, won't be inserted
SELECT * FROM TICKS; -- should show 2 records
```

feat(web-console): add `DEDUP` support in `Copy schema to clipboard`

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

- Add `DEDUP` support in `Copy schema to clipboard` [#235](https://github.com/questdb/ui/pull/235)
- Fix table schema form on already existing tables [#236](https://github.com/questdb/ui/pull/236)
- Fix query execution when line comments are present [#231](https://github.com/questdb/ui/pull/231)

release(web-console): 0.3.2

---

packages/browser-tests/cypress/integration/console/editor.spec.js

Temporarily skip some tests that result in spurious issues not related to the code itself (i.e. key event issues in Monaco).

chore(browser-tests): skip some editor tests

---

packages/web-console/src/components/icons/import.tsx

Adjust the syntax of the new Import icon so that it reacts to the fill definition of the parent accordingly.

chore(web-console): Adjust the SVG syntax of Import icon

---

packages/web-console/src/scenes/Editor/Monaco/index.tsx
packages/web-console/src/scenes/Editor/Monaco/questdb-sql/createSchemaCompletionProvider.ts

This PR addresses two issues:
1. By dynamically adjusting the left gutter (the space with line numbers and decoration glyphs) it ensures the green "Run" button stays in a fixed position no matter how many lines in the editor there are. When the line number changes in digit count (i.e. from 99 to 100), gutter width expands or contracts accordingly to ensure visual consistency.
2. The way the green "Run" (play) is rendered has been changed to ensure it always looks the same no matter the browser and operating system.  
Fixes https://github.com/questdb/ui/issues/251

fix(web-console): Fix issues with `Run` button in editor gutter

---

packages/web-console/src/scenes/Console/index.tsx

The current panel configuration saves the alignment incorrectly - vertical (editor+schema and result) is where horizontal (schema and editor) should be.

fix(web-console): fix results and editor panel size configs

---

packages/web-console/src/scenes/Editor/Monaco/questdb-sql/createSchemaCompletionProvider.ts

Disable triggering autocomplete on newlines, when the cursor is either on the beginning of the new line or indented from the previous one.
Before:
After:

fix(web-console): do not trigger autocomplete on newlines

---

packages/web-console/src/scenes/Editor/Monaco/index.tsx

When QuestDB instance is down and then restarted, clicking the "Refresh" icon on the `Tables` menu bar will result in getting duplicates (or, in some cases, triplicates) of autocomplete suggestions.
Steps to replicate and test the correct behavior:
1. Load the Web Console.
2. Stop the running QuestDB instance.
3. Run any query or click "Refresh" icon on the `Tables` menu bar.
4. Start QuestDB instance again.
5. Run any query again or refresh the table list. Autocomplete should not show any duplicates (it will show up duplicates on `main`).
Screenshot of the issue:

fix(web-console): get rid of autocomplete duplicates

---

packages/web-console/src/scenes/Import/ImportCSVFiles/files-to-upload.tsx

Fixes https://github.com/questdb/ui/issues/270
Since CSV Import allows importing files with the same names multiple times, we've stopped using filenames as their identifier, which means this is what we check against when updating their settings when user changes them. The following bug was a leftover from the older times.
Steps to replicate:
1. Upload the file attached in the original issue.
2. Select "Force header" in the `Settings` drawer to.
3. The table should be created with proper column names, inferred from the CSV file header.

fix(web-console): file settings not being passed to API

---

packages/web-console/src/providers/EditorProvider/index.tsx

Querying the buffer store through Dexie's live query caused frequent re-renders on any component that used the EditorProvider Context as each character entered into the buffer would trigger a change in state.
The flickering borders indicate components that are re-rendered. 
Before:
https://github.com/questdb/ui/assets/7108642/c4da847e-d81d-47f1-b32b-2658e9a8b26d
After:
https://github.com/questdb/ui/assets/7108642/025477f7-8e31-44b3-8b13-6e5e852663d7
The buffer is still being persisted correctly into indexedDB.
https://github.com/questdb/ui/assets/7108642/4130f759-3719-4a2a-8904-9960e8373c61

fix(web-console): combine buffer init into a single hook

---

packages/react-components/src/components/Button/index.stories.tsx
packages/react-components/src/components/Button/index.tsx

Our Button consists of 3 components typically, A base button that handles the input; A div wrapper ,the Prefix, on top that is used to control the layout of the icon; An optional prefix icon that is used to display an icon when specified. Currently, we do not disable pointer events on the Prefix which results in input events being erroneously captured and attributed to it. This PR addresses the issue by disabling all pointer events on the Prefix so that they get registered by the base button instead.
Verified using #276 
Before: 
https://github.com/questdb/ui/assets/7108642/07de4703-c071-4361-91a0-0371f7bef235
After:
https://github.com/questdb/ui/assets/7108642/7ed0f2c1-1232-4103-abe8-0e22f9a76d26

chore(react-components): disable input on prefix

---

packages/web-console/src/scenes/Schema/Row/index.tsx

fix(web-console): show an icon next to non-designated timestamp columns

---

packages/web-console/package.json
packages/web-console/src/utils/questdb.ts

- excluding token refresh from query execution time
- schedule the wait for token refresh only if there is a pending token refresh
Not sure if we should also display token refresh time (only if there was token refresh)?
Raised an issue, it can be implemented later if we think it is needed:
https://github.com/questdb/ui/issues/283

fix(web-console): align displayed timings with real fetch time

---

packages/web-console/src/scenes/Editor/Monaco/index.tsx
packages/web-console/src/utils/questdb.ts

Server introduced a new response type for successful INSERT and UPDATE statements, error response is unchanged.
INSERT: `{"dml": "OK"}`
UPDATE: `{"dml": "OK", "updated": 4}`
Web console should handle this new response type.

fix(web-console): handling DML response for INSERT and UPDATE

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

- Add bundle size watcher task [#288](https://github.com/questdb/ui/pull/288)
- Add PostHog support [#284](https://github.com/questdb/ui/pull/284)
- Support varchar column type [#281](https://github.com/questdb/ui/pull/281)
- Handling DML response for INSERT and UPDATE
[#290](https://github.com/questdb/ui/pull/290)

release(web-console): 0.4.2

---

packages/web-console/src/components/TableSchemaDialog/column.tsx

Timestamp formating is non-trivial. Link should help to users.
Styling isn't great, so some adjustments is welcome. I couldn't figure out the right component/class to make the docs link icon aligned with the text above it :(
Before:
After:

chore(web-console): include link to timestamp formats docs in CSV import schema editor

---

packages/web-console/src/index.html
packages/web-console/src/js/console/quick-vis.ts
packages/web-console/src/modules/OAuth2/views/login.tsx
packages/web-console/src/modules/ZeroState/start.tsx
packages/web-console/src/providers/AuthProvider.tsx
packages/web-console/src/providers/SettingsProvider/index.tsx
packages/web-console/src/scenes/Import/ImportCSVFiles/upload.tsx
packages/web-console/src/utils/questdb.ts
packages/web-console/webpack.config.js

The web console to use relative URLs to make it possible deploying it under a context path.
The change consists of 2 parts:
- changing webpack config not to use ASSET_PATH (publicPath: "auto" means webpack will generate relative URLs)
- changing the code not to prefix URLs with `window.location`, this makes them relative

chore(web-console): use relative URLs

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

releasing v0.4.4
- Start EE telemetry [#294](https://github.com/questdb/ui/pull/294)
- Use relative URLs [#299](https://github.com/questdb/ui/pull/299)
- Include link to timestamp formats docs in CSV import schema editor
[#295](https://github.com/questdb/ui/pull/295)
- Copy grid cell content to clipboard on MacOS
[#297](https://github.com/questdb/ui/pull/297)

release(web-console): 0.4.4

---

packages/web-console/src/modules/ZeroState/start.tsx

Remove QuestDB Cloud info from web console.
We might use the real estate to communicate other things, but that will probably require more thinking - like rotating a bunch of tips, "did you know that .. ?", etc.

chore(web-console): remove cloud info

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

- Add Telemetry tests [#298](https://github.com/questdb/ui/pull/298)
- Add WAL suspension info and resolution logic, add OS configuration warnings
and resolution info [#291](https://github.com/questdb/ui/pull/291)
- Improve integration testing [#305](https://github.com/questdb/ui/pull/305)

release(web-console): 0.5.0

---

packages/browser-tests/cypress/integration/console/schema.spec.js
packages/web-console/src/components/CreateTableDialog/index.tsx
packages/web-console/src/components/TableSchemaDialog/dialog.tsx
packages/web-console/src/components/Tooltip/index.tsx
packages/web-console/src/scenes/Schema/Row/index.tsx
packages/web-console/src/scenes/Schema/SuspensionDialog/index.tsx
packages/web-console/src/scenes/Schema/index.tsx

- Remove the `+` icon in the Tables header - it will come back when the Create Table view is opened in the left side of the screen.
- Fix for clicking the disabled `Create Table` icon in read-only mode - it should not be possible to show it and clicking the icon should be a no-op.
- Fix table filter: it should show only the tables with a match and highlight.

chore(web-console): Small UI fixes related to Tables

---

packages/browser-tests/cypress.config.js

The small adjustment in the Cypress config allows for one test retry in case the Monaco Editor is initialized in a different order and although the elements we check for are already mounted, user can't type anything yet. This happens on the CI alone and cannot be reliably reproduced on any other platform.
An arbitrary wait timeout has the same positive effect, but it's sub-optimal and would slow down text execution significantly, since there is no need to wait always, just in case there is a rare spurious failure.

chore(browser-tests): adjust cypress config to allow for a single retry

---

packages/web-console/src/modules/OAuth2/utils.ts
packages/web-console/src/providers/AuthProvider.tsx
packages/web-console/src/providers/SettingsProvider/types.ts

configurable redirect URI and scope for OIDC integration
requires https://github.com/questdb/questdb-enterprise/pull/472

feat(ui): configurable redirect URI and scope for OIDC integration

---

packages/web-console/src/scenes/Schema/SuspensionDialog/index.tsx

When the WAL table is suspended, user can click on the `Suspended` button next to the table name to diagnose the problem. The current number of transactions behind is derived from `writerLagTxnCount` property, which gives incorrect results. This PR fixes it by switching to the difference between sequencer and writer txn counts.

fix(web-console): fix suspension lag count

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

- Configurable Redirect URI and scope for OIDC integration
[#323](https://github.com/questdb/ui/pull/323)
- Run Console tests with Auth [#310](https://github.com/questdb/ui/pull/310)
- Fix suspension lag count [#327](https://github.com/questdb/ui/pull/327)

release(web-console): 0.5.2

---

packages/web-console/src/scenes/Schema/Row/index.tsx

Display the `Copy` button for suspended tables too - it's currently not visible.

fix(web-console): Display `Copy` for suspended tables

---

packages/browser-tests/cypress/commands.js
packages/browser-tests/cypress/integration/console/editor.spec.js
packages/web-console/src/scenes/Editor/Monaco/index.tsx
packages/web-console/src/scenes/Editor/Monaco/utils.ts

SQL Editor should properly highlight queries containing line comments with the green vertical line and execute correctly in various configurations:
- at the beginning of the query (one or more lines)
- within the query itself (i.e. in the middle, one or more lines)
Example queries that should be executed and highlighted correctly:
```sql
-- line comment 1
-- line comment 2
SELECT x FROM long_sequence(1000);
SELECT
x
-- y
FROM
long_sequence(1000);
SELECT
x
-- y
-- Z
FROM
long_sequence(1000);
```
Screen recording of the correct behavior:
https://github.com/user-attachments/assets/0611c1d7-6809-4e98-9f0d-278701db7b21

fix(web-console): handle line comments in SQLs

---

packages/web-console/src/scenes/Editor/Monaco/tabs.tsx

- Remove the CTA tooltip, add text
- Add the active (opened) CTA state
Screenshot:

chore(web-console): Tab History UI updates

---

packages/browser-tests/cypress/integration/console/editor.spec.js
packages/web-console/src/scenes/Editor/Monaco/index.tsx
packages/web-console/src/scenes/Editor/Monaco/utils.ts

This PR fixes the issues with query highlighting where line comments are in place - most importantly before the statement, like so:
This should work when the comment contains the actual text after the `--` mark, as well as it's empty (`--` only).

fix(web console): handling comments in SQL editor highlights

---

.github/workflows/check_oss_submodule.yml

Swapped out `pip` for `uv` and fixed the pip install clash with Ubuntu's "thou shall not install global packages" settings.

ci: fix check oss submodule

---

packages/web-console/src/components/CopyButton/index.tsx
packages/web-console/src/providers/EditorProvider/index.tsx
packages/web-console/src/scenes/Editor/Monaco/index.tsx
packages/web-console/src/scenes/Editor/Monaco/query-in-notification.tsx
packages/web-console/src/scenes/Editor/Monaco/questdb-sql/conf.ts
packages/web-console/src/scenes/Notifications/index.tsx
packages/web-console/src/store/Query/types.ts

- Scrolling to error position in the editor
- Truncate query text in Notifications bar, add Copy CTA
- Switch the green "play" triangle in the editor margin to "stop" when query is running. clicking on the "stop" button will cancel.
- Proper multi-tab error support. Error markers (highlight + squiggly lines) in one tab should not spill over to the next one, they should be separate.
- Remove `=` as word delimiter, so that expressions like `==` can be highlighted as errors (since they can now be tokens)

chore(web-console): UX improvements around editor

---

packages/web-console/src/scenes/Layout/index.tsx
packages/web-console/src/scenes/News/image-zoom.tsx
packages/web-console/src/scenes/News/index.tsx
packages/web-console/src/scenes/News/thumbnail.tsx
packages/web-console/src/store/Console/actions.ts
packages/web-console/src/store/Console/reducers.ts
packages/web-console/src/store/Console/selectors.ts
packages/web-console/src/store/Console/types.ts
packages/web-console/src/utils/questdb.ts

Add an image overlay mode for News thumbnails. The mode is activated on hover with a slight delay and deactivated when user mouse goes out of the thumbnail.

feat(web-console): Add news image zoom

---

packages/web-console/src/scenes/Editor/Monaco/questdb-sql/language.ts

chore: highlight integer numbers that include `_` (underscore) separator

---

packages/web-console/src/components/CreateTableDialog/index.tsx
packages/web-console/src/components/TableSchemaDialog/dialog.tsx
packages/web-console/src/components/TableSchemaDialog/types.ts
packages/web-console/src/scenes/Import/ImportCSVFiles/files-to-upload.tsx
packages/web-console/src/scenes/Import/ImportCSVFiles/index.tsx
packages/web-console/src/scenes/Import/ImportCSVFiles/types.ts
packages/web-console/src/scenes/Schema/Table/index.tsx
packages/web-console/src/scenes/Schema/formatTableSchemaQueryResult.ts
packages/web-console/src/scenes/Schema/index.tsx
packages/web-console/src/utils/formatTableSchemaQuery.ts
packages/web-console/src/utils/questdb.ts

- TTL shows up in "Copy table schema to clipboard"
- missing: Create Table dialog should allow setting TTL

Add the TTL feature to tables

---

README.md
docs/local-development-setup.md
packages/web-console/README.md
packages/web-console/src/store/db.ts
packages/web-console/webpack.config.js

When a context path is configured on server side, we can set an env var for dev server to set the same context path to be used by the proxy.
For example:
```
CONTEXT_PATH=/instance2
export CONTEXT_PATH
yarn workspace @questdb/web-console start
```
To get rid of the context path:
```
unset CONTEXT_PATH
yarn workspace @questdb/web-console start
```

chore(ui): webpack dev server proxy to take context path from env variable

---

packages/web-console/src/providers/AuthProvider.tsx

Kick the user out of the web console if the access token has expired and there is no refresh token.
It is completely valid not to allow token refresh in the OAuth2/OIDC provider.
If token refresh is disabled, the refresh token is omitted from the token response, and the web console cannot refresh expired access tokens automatically.
Currently when this happens, the web console attempts to login with the expired token, and the server rejects it.
The change is not to send the expired token to QuestDB, instead we simply kick the user out, and force a login to get fresh tokens.

fix(ui): kick user out if access token expired and there is no refresh token

---

packages/web-console/src/scenes/Schema/index.tsx

Make use of the recently available statement to pull the table schema, instead of stitching it together on the client side.
Note: The old logic is still required for Create Table UI, and this is why it's not deleted.
NW EDIT: Fixes https://github.com/questdb/ui/issues/354

chore(web-console): use `SHOW CREATE TABLE` in `Copy schema to clipboard`

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

- WAL Metrics for tables [#352](https://github.com/questdb/ui/pull/352)
- Add TTL feature to tables [#365](https://github.com/questdb/ui/pull/365)
- webpack dev server proxy to take context path from env variable
[#371](https://github.com/questdb/ui/pull/371)
- use `SHOW CREATE TABLE` in `Copy schema to clipboard`
[#369](https://github.com/questdb/ui/pull/369)
- Make autocomplete case insensitive
[#366](https://github.com/questdb/ui/pull/366)
- kick user out if access token expired and there is no refresh token
[#373](https://github.com/questdb/ui/pull/373)

release(web-console): 0.7.0

---

packages/web-console/src/scenes/Editor/Metrics/index.tsx
packages/web-console/src/scenes/Editor/Metrics/metric.tsx
packages/web-console/src/store/buffers.ts

Symptoms fixed:
- if we change widget keys, old keys were permanently stuck in storage, making it impossible to render 0-day screen (add new metric)
- when metric was deleted and another metric jumps into deleted metric's position, we would update everything for new metric position except for the fetcher, which remained inert to `widgetConfig` change

chore(ui): fix metric state, corrupted by deleting a metric & loading of unknown metric types

---

.github/workflows/ci.yml
packages/web-console/src/modules/OAuth2/pkce.ts
packages/web-console/src/modules/OAuth2/utils.ts
packages/web-console/src/providers/AuthProvider.tsx
packages/web-console/src/providers/SettingsProvider/types.ts
packages/web-console/src/utils/localStorage/types.ts

If the `state` parameter is enabled in settings (`acl.oidc.state.required=true`), the Web Console generates a state value, and sends it to the Authorization Server while requesting authorization code.
The `state` is expected to be sent back to the Web Console together with the authorization code, the Web Console checks if the value of the `state` parameter is the same.
If not, it sends the user to the logout screen.

feat(ui): support for OAuth2 state parameter

---

packages/web-console/CHANGELOG.md
packages/web-console/package.json

- Add button to copy query plans and result sets to clipboard in markdown format [#393](https://github.com/questdb/ui/pull/393)
- Escape table name for SHOW CREATE TABLE [#398](https://github.com/questdb/ui/pull/398)

release(web-console): 0.7.6

---

packages/browser-tests/cypress/integration/console/editor.spec.js
packages/browser-tests/cypress/integration/console/schema.spec.js
packages/web-console/src/components/Tree/index.tsx
packages/web-console/src/scenes/Schema/Row/index.tsx
packages/web-console/src/scenes/Schema/Table/index.tsx
packages/web-console/src/scenes/Schema/VirtualTables/index.tsx
packages/web-console/src/scenes/Schema/index.tsx
packages/web-console/src/scenes/Schema/localStorageUtils.ts
packages/web-console/src/scenes/Schema/table-icon.tsx
packages/web-console/src/styles/_grid.scss

- Adds new icon for non-partitioned tables
- Adds new icon for materialized views
- Adds new icon for symbol type columns
- Adds "Indexed", "Symbol capacity", and "Cached" information under symbol type columns
- Adds "storage details" folder under tables
- Adds "base tables" folder under materialized views
- Fixes geohash column type icon
- Fixes the issue about tables/materialized views being collapsed after a scroll

feat(web-console): add storage details, persistent expand states, symbol details

---

packages/browser-tests/cypress/integration/console/editor.spec.js
packages/web-console/src/providers/EditorProvider/index.tsx
packages/web-console/src/scenes/Editor/Metrics/index.tsx
packages/web-console/src/scenes/Editor/Monaco/index.tsx
packages/web-console/src/scenes/Editor/index.tsx
packages/web-console/src/store/buffers.ts

- Fixes the problem about incorrectly saving `editorViewState` in a metrics buffer when buffers are updated via reorder/close etc.
- Fixes unresponsiveness when web console gets `query` query param, and the active buffer is a metrics tab

fix(web-console): open a new tab when query param exists and metrics tab is open

---

packages/web-console/src/js/console/grid.js

Fixes https://github.com/questdb/ui/issues/227
- Call `scroll()` after scrolling grid by dragging scrollbar to prevent unresponsiveness, just as in `render()`
- Check if `focusedCell` and `activeRow` is the actual item with `focusedRowIndex` before applying focus styles. This prevents focused row and cell to be shown indefinitely as the user scrolls the list.

fix(web-console): grid unresponsiveness after scroll

---

packages/browser-tests/cypress/integration/console/grid.spec.js
packages/browser-tests/cypress/integration/console/schema.spec.js
packages/web-console/src/scenes/Editor/Monaco/query-in-notification.tsx
packages/web-console/src/scenes/Editor/QueryResult/index.tsx
packages/web-console/src/scenes/Notifications/Notification/SuccessNotification/index.tsx
packages/web-console/src/scenes/Notifications/Notification/styles.tsx
packages/web-console/src/scenes/Notifications/index.tsx
packages/web-console/src/scenes/Schema/Row/index.tsx
packages/web-console/src/scenes/Schema/VirtualTables/index.tsx

- Fix JIT compiled query icon shrink problem
- Fix notifications being collapsed when there are multiple
- Long queries can be scrolled horizontally in query history
- Move copy query button to the left of query (no need to scroll all the way to the end of a long query for copying)
- Change wording from "row" to "rows" when there is no row in result set
- Fix failing materialized view invalidation test

fix(web-console): jit compiled icon shrink problem and notifications height

---

packages/web-console/src/utils/questdb/client.ts

`.json()` reads the whole response body, and then parses it as JSON. 
Our network time should include the time elapsed while waiting for the whole body, but should not include the parsing time. Thus, replaced `.json()` with `.text()` and then `JSON.parse()`

fix(web-console): wait for all body to be streamed before calculating network time

---

packages/browser-tests/cypress/integration/console/topbar.spec.js
packages/browser-tests/cypress/integration/console/warnings.spec.js

- Changes instance type from `Production` to `Testing` in `topbar.spec.js`
- Executes queries for adding warnings directly without interacting with the UI

test(web-console): flakiness and case updates

---

packages/browser-tests/cypress/commands.js
packages/browser-tests/cypress/integration/console/topbar.spec.js
packages/browser-tests/cypress/integration/enterprise/oidc.spec.js
packages/browser-tests/cypress/integration/enterprise/topbar.spec.js
packages/web-console/src/scenes/Notifications/Notification/ErrorNotification/index.tsx
packages/web-console/src/scenes/Notifications/Notification/InfoNotification/index.tsx
packages/web-console/src/scenes/Notifications/Notification/NoticeNotification/index.tsx
packages/web-console/src/scenes/Notifications/Notification/SuccessNotification/index.tsx
packages/web-console/src/utils/questdb/client.ts
run_browser_tests.sh
run_ent_browser_tests.sh

The web console queries the user's permissions to determine if they should be able to edit instance name/type/desc or not.
This is done by executing `show permissions username`.
However, we should be executing `show permissions 'username'` instead, as the former query fails if the username contains a dot (`.`), such as `john.doe`.
The PR also fixes issues with tests.

fix(ui): fix for users with a `.` in their name are unable to edit instance name (enterprise)

---

packages/web-console/src/scenes/Editor/Metrics/index.tsx
packages/web-console/src/scenes/Editor/index.tsx

Reworked the state management of this component, ensuring updates all go through the `updateBuffer` call, no redundant local state, no unnecessary rerenders, no mutations on context values.
- Metrics component was getting the buffers object from Dexie, setting a local state, and was not properly syncing local state with the storage.
- In some cases, we were running effect to set the local state because context value changed ->  running effect to set the context value -> .... This was causing infinite loops. -> removed redundant local state and effects
- We had a focus listener but it did not have any effect -> removed
- We had a visibility check but ref was being set only when telemetry is disabled -> reversed, it is set when telemetry is enabled

fix(web-console): prevent infinite state updates in metrics

---

packages/browser-tests/cypress/integration/console/schema.spec.js
packages/web-console/src/scenes/Editor/Monaco/questdb-sql/createSchemaCompletionProvider.ts
packages/web-console/src/scenes/Schema/Row/index.tsx
packages/web-console/src/scenes/Schema/VirtualTables/index.tsx
packages/web-console/src/scenes/Schema/VirtualTables/utils.ts
packages/web-console/src/scenes/Schema/index.tsx
packages/web-console/src/store/Query/reducers.ts
packages/web-console/src/store/Query/selectors.ts
packages/web-console/src/store/Query/types.ts
packages/web-console/src/utils/questdb/client.ts

Enhanced the table filter in the Schema panel to search both `table names` & `column names`. When a column matches the search query, the table automatically expands (in-memory only) to show the matching columns.
- **Filter logic**: Updated table filtering to include column name matches using existing Redux `allColumns` data
- **Auto-expansion**: Tables with matching columns now auto-expand their table row AND columns folder during search
- **State management**: Search-driven expansions are purely in-memory and never persist to localStorage
- **Race condition fix**: Added cleanup mechanism (`isCancelled` flag) to prevent stale async operations from causing incorrect expansion states during rapid input changes
1. **Column matching**: Uses `allColumns` from Redux store (already fetched via …

feat(web-console): Add column name search to Schema filter
